### ISSUE TITLE
Feature Request: Uke

### ISSUE THREAD

**Issue by jgarte** [newlandsvalley/chord-builder#3]
https://www.youtube.com/watch?v=sfmAeijj5cM

**Comment by newlandsvalley** [comment]
I've had a brief look at your tenor guitar branch - it looks very promising so far - thanks very much.  I will review the changes in more detail when I get time, but one thing concerns me particularly at the moment.  Whereas bass guitar differs considerably from guitar because a chord is actually played as an arpeggio, all of guitar, tenor guitar and uke are pretty much the same.  The number of strings and the tuning differs, but most of the rest is more or less identical - for example a barre and/or a single finger position on a string.

I'd like to propose that we first merge tenor guitar once it's complete, but then, before attempting uke, we refactor and try to extract common patterns into some sort of common guitar modules.

**Comment by jgarte** [comment]
I was thinking the exact same thing as I was going through it. There's a lot of duplicate code now that can probably be consolidated into some common utility library for string or fretted instruments.

**Comment by jgarte** [comment]
@newlandsvalley Just adding a tag here that this issue is dependent or blocked until #4 gets resolved.

**Comment by newlandsvalley** [comment]
Very many thanks, @jgarte.
